name: Checkout & Build App

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  # check:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     should_build: ${{ steps.check-updates.outputs.has_changes }}
  #   steps:
  #     - name: Check for updates 🌏
  #       id: check-updates
  #       run: |
  #         last_run=$(curl -s "https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/runs?status=completed&per_page=1" | jq -r '.workflow_runs[0].created_at')
  #         kotatsu_updated=$(curl -s "https://api.github.com/repos/KotatsuApp/Kotatsu/commits?since=$last_run" | jq '. | length')
  #         parsers_updated=$(curl -s "https://api.github.com/repos/KotatsuApp/kotatsu-parsers/commits?since=$last_run" | jq '. | length')
  #         if [ "$kotatsu_updated" -gt "0" ] || [ "$parsers_updated" -gt "0" ]; then
  #           echo "has_changes=true" >> $GITHUB_OUTPUT
  #         else
  #           echo "has_changes=false" >> $GITHUB_OUTPUT
  #         fi

  build:
    # needs: check
    # if: needs.check.outputs.should_build == 'true'
    runs-on: ubuntu-22.04
    outputs:
      new_tag: ${{ steps.tagger.outputs.new_tag }}
    steps:
      - name: Checkout repository 🚀
        uses: actions/checkout@v3
        with:
          clean: true
          fetch-depth: 0

      - name: Pull upstream 🌏
        run: |
          git remote add kotatsu https://github.com/KotatsuApp/Kotatsu.git
          git fetch kotatsu
          git checkout -b kotatsu kotatsu/devel

      - name: Setup Java enviroments 🚀
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK 🚀
        uses: android-actions/setup-android@v3

      - name: Grant permissions 🚀
        run: chmod a+x gradlew

      - name: Generate build number 📆
        id: tagger
        run: |
          echo "new_tag=$(date +'%s')" >> $GITHUB_OUTPUT
          echo "formatted_date=$(date +'%s')" >> $GITHUB_OUTPUT

      - name: Fixing for Nightly APK 🔧
        run: |
          sed -i '/<SwitchPreferenceCompat/,/android:title="@string\/allow_unstable_updates"/d' app/src/main/res/xml/pref_about.xml
          sed -i 's/now\.format("yyMMdd")/now.format("yyyyMMdd")/' app/build.gradle
          sed -i 's/org\.gradle\.jvmargs=-Xmx1536M -Dkotlin\.daemon\.jvm\.options\\="-Xmx1536M"/org.gradle.jvmargs=-Xmx8192M -Dkotlin.daemon.jvm.options\\="-Xmx8192M"/' gradle.properties
      - name: Change kotatsu-parsers source
        run: |
          sed -i 's/com\.github\.KotatsuApp/com.github.iwakurra/' app/build.gradle
      - name: Change sign config for nightly to debug (cause i'm don't have official keys)
        run: |
          sed -i '/nightly {/,/}/c\
                  nightly {\
                          initWith debug\
                          minifyEnabled true\
                          shrinkResources true\
                          proguardFiles getDefaultProguardFile('"'"'proguard-android-optimize.txt'"'"'), '"'"'proguard-rules.pro'"'"'\
                          applicationIdSuffix = '"'"'.nightly'"'"'\
                  }' app/build.gradle

      - name: Building Nightly APK 💻
        run: |
          ./gradlew assembleNightly -DparsersVersionOverride=$(curl -s https://api.github.com/repos/iwakurra/kotatsu-parsers/commits/master -H "Accept: application/vnd.github.sha" | cut -c -10)
        continue-on-error: false

      # - name: Building Nightly APK (Attempt 2) 💻
      #   run: >-
      #     if [ ! -f app/build/outputs/apk/nightly/app-nightly-unsigned.apk ]; then
      #       pkill -f java &&
      #       ./gradlew assembleDebug -DparsersVersionOverride=$(curl -s https://api.github.com/repos/iwakurra/kotatsu-parsers/commits/master -H "Accept: application/vnd.github.sha" | cut -c -10);
      #     else
      #       echo "✅ Nightly APK already exists, skipping build attempt 2";
      #     fi
      #   continue-on-error: true

      # - name: Building Nightly APK (Attempt 3) 💻
      #   run: >-
      #     if [ ! -f app/build/outputs/apk/nightly/app-nightly-unsigned.apk ]; then
      #       pkill -f java &&
      #       ./gradlew assembleDebug -DparsersVersionOverride=$(curl -s https://api.github.com/repos/iwakurra/kotatsu-parsers/commits/master -H "Accept: application/vnd.github.sha" | cut -c -10);
      #     else
      #       echo "✅ Nightly APK already exists, skipping build attempt 3";
      #     fi
      #   continue-on-error: false

      # - name: Packaging Nightly APK 💻
      #   uses: ilharp/sign-android-release@v1
      #   id: sign_app
      #   with:
      #     releaseDir: app/build/outputs/apk/nightly
      #     signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
      #     keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
      #     keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      #     keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      #     buildToolsVersion: 35.0.0

      # - name: Prepare to Upload 🌏
      #   run: |
      #     mv ${{steps.sign_app.outputs.signedFile}} app/build/outputs/apk/nightly/release.apk
      #     echo "SIGNED_APK=app/build/outputs/apk/nightly/release.apk" >> $GITHUB_ENV
      #     echo "MAPPING_FILE=app/build/outputs/mapping/nightly/mapping.txt" >> $GITHUB_ENV

      # - name: Get latest changes 📑
      #   id: changelog
      #   run: |
      #     curl -o commit.py -L https://raw.githubusercontent.com/KotatsuApp/Kotatsu-nightly/nightly/.github/assets/commit.py
      #     python3 commit.py
          
      #     CHANGELOG=$(cat commits.txt)
      #     echo "content<<EOF" >> $GITHUB_OUTPUT
      #     echo "$CHANGELOG" >> $GITHUB_OUTPUT
      #     echo "EOF" >> $GITHUB_OUTPUT

      - name: Create new GH Release + Uploading 🌏
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ steps.tagger.outputs.new_tag }}
          name: "Nightly Build ${{ steps.tagger.outputs.new_tag }}"
          body: |
            Automated nightly build with my kotatsu-parsers generated on ${{ steps.tagger.outputs.formatted_date }}
            
          files: |
            app/build/outputs/apk/nightly/app-nightly.apk
          # ${{ env.SIGNED_APK }}
          # ${{ env.MAPPING_FILE }}
          prerelease: false

  # update:
  #   needs: build
  #   if: needs.check.outputs.should_build == 'true'
  #   runs-on: ubuntu-22.04
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: nightly
  #         fetch-depth: 0

  #     - name: Update Build Number 📆
  #       run: |
  #         VERSION_NUMBER="${{ needs.build.outputs.new_tag }}"
  #         COUNTER_LINKS=""          
  #         for (( i=0; i<${#VERSION_NUMBER}; i++ )); do
  #           DIGIT="${VERSION_NUMBER:$i:1}"
  #           COUNTER_LINKS+="[![Download](https://rule34.xxx/counter/$DIGIT.gif)](https://github.com/KotatsuApp/kotatsu-nightly/releases/latest) "
  #         done
  #         sed -i "/### <img src=\".\/.github\/assets\/app_icon.png\" alt=\"Kotatsu Logo\" width=\"16\" style=\"vertical-align: bottom;\"\/> Download <img src=\".\/.github\/assets\/app_icon.png\" alt=\"Kotatsu Logo\" width=\"16\" style=\"vertical-align: bottom;\"\/>/,/div>/c\### <img src=\".\/.github\/assets\/app_icon.png\" alt=\"Kotatsu Logo\" width=\"16\" style=\"vertical-align: bottom;\"\/> Download <img src=\".\/.github\/assets\/app_icon.png\" alt=\"Kotatsu Logo\" width=\"16\" style=\"vertical-align: bottom;\"\/>\n\n${COUNTER_LINKS}\n\n<div align=\"left\">\n\n* Nightly build can be downloaded from the [GitHub Releases](https://github.com/KotatsuApp/Kotatsu-Nightly/releases). Application has a built-in self-updating feature.\n* If you want to download a stable Kotatsu release please refer to the [main Kotatsu repository](https://github.com/KotatsuApp/Kotatsu?tab=readme-ov-file#download).\n\n</div>" README.md

  #     - name: Update Docs + Commit 🌏
  #       run: |
  #         git config --local user.email "bot@kotatsu.app"
  #         git config --local user.name "kotatsu-bot"
  #         if [[ -n $(git status -s) ]]; then
  #           git add README.md
  #           git commit -m "Bump build number to ${{ needs.build.outputs.new_tag }}"
  #           git push origin nightly
  #         else
  #           echo "No changes to push!"
  #         fi
